version: '3'
services:
  bot:
    container_name: multiSVBot
    build: .
    depends_on:
    - "db"
    volumes:
      - ./application.properties:=/config/application.properties
    command: --spring.config.location=/config/application.properties

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres