version: '3'
services:
  bot:
    container_name: multiSVBot
    build: .
    depends_on:
      - "db"
    ports:
      - 8080:8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_JPA_SHOW_SQL: "false"

      USERNAME: mutliSVTestBot
      TOKEN: "985543338:AAF0sBsWLRQiPYpdItyU5iEEfU9AU2KxQzE"
      CUPS_HOST: localhost
      CUPS_PORT: 631
      PAGE_PRICE: 2
      SBERBANK_USERNAME: multiservis22-api
      SBERBANK_PASSWORD: multiservis22
      BASE_URL: "https://payment.printomat.online"
      IS_ENBALE_QR: "false"
      COMPANY_NAME: Мультисервис
      COMPANY_LOCATION: "ТЦ Лидер"
      EMBEDDED_MAP: '<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2382.410353817338!2d83.67436331595862!3d53.33591018319387!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x42dda48d940b3e17%3A0x87a80bd3a361a693!>'
      COMPANY_WORKING_TIME: "пн-пт 10-22"
      IS_ENABLE_VK: "false"
      VK_GROUP_ID: ""
      VK_GROUP_TOKEN: ""
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres