name: Docker Image CI

on:
  push:
    branches: [ master ]
    
jobs:

  build:

    runs-on: self-hosted

    steps:
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag registry.chardware.duckdns.org/printing-bot:$(PRINT_BOT_VERSION=1)
    - name: push to registry
      run:  docker push registry.chardware.duckdns.org/printing-bot:$(PRINT_BOT_VERSION=1)
    - name: update version
      run: export PRINT_BOT_VERSION=$(($PRINT_BOT_VERSION+1))

